config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :companies
  resources :employee_emails
  resources :employee_email_managers

  get "/employees/", to: 'employees#index', as: 'employee'

 

  root 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :quotes, dependent: :destroy
end

app/models/employee_email.rb
class EmployeeEmail < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  
  def index
    #THIS IS ACTING A NEW CONTROLLER WOULD, CREATING COMPANY ENTRY IN DATABASE
    @company = Company.new
  end

  def show
    @company = Company.find(params[:id])
    @quotes = Quote.all
  end

  def new
    @companies = Company.all
  end

  def dashboard
    @companies = Company.all
  end

  def edit
    @company = Company.find(params[:id])
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:notice] = 'Your company information has been added'
      session[:current_company_id] = @company.id
      redirect_to new_quote_path
    else
      render action: 'index'
     end
  end

  def update
    @company = Company.find(params[:id])
    if @company.update_attributes(company_params)
      flash[:notice] = 'Your company was updated'
      redirect_to employee_path
    else
      render action: 'new'
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to employee_path, notice: 'Company was successfully destroyed.' }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Remember to update if/when company table has more columns added
    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:id, :email, :companyname, :name, :phone)
    end
end

app/controllers/employee_email_managers_controller.rb
class EmployeeEmailManagersController < ApplicationController


  def index
    @emails = EmployeeEmail.all
    @email = EmployeeEmail.new
  end

  # def show
  #   @email = EmployeeEmail.find(params[:id])
  # end

  def create
    @email = EmployeeEmail.new(email_params)

    if @email.save
      flash[:notice] = 'Your email information has been added'
      redirect_to employee_email_managers_path
    else
      render action: 'new'
     end
  end

  def destroy
    @email = EmployeeEmail.find(params[:id])
    if @email.present?
      @email.destroy
    end
    redirect_to employee_email_managers_path
  end

  private

    def email_params
      params[:employee_email].permit(:name, :email)
    end
end

app/controllers/employee_emails_controller.rb
# class EmployeeEmailsController < ApplicationController

#     def destroy
#         @email.destroy
#         respond_to do |format|
#             format.html { redirect_to employee_email_managers_path, notice: 'Line-item was successfully removed.' }
#         end
#     end
    
#     end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  #this is coppied directly from quotes_controller
  def index
    @quotes = Quote.all
    @companies = Company.all
  end

  def show
    @quote = Quote.find[params[:id]]
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  def index
    @quotes = Quote.all

  end

  def show
    @quotes = Quote.find(params[:company_id])
  end

  def new
    @quotes = Quote.all
    @quote = Quote.new
  end

  def edit
    @quote = Quote.find(params[:id])
  end

  def create
    @quote = Quote.new(quote_params)
    @quote.company_id = session[:current_company_id]
    if @quote.save
      flash[:notice] = 'Your quote information has been added'
      send_notification
      redirect_to quotes_path
    else
      render action: 'new'
     end
  end

  def update
    @quote = Quote.find(params[:id])
    if @quote.update_attributes(quote_params)
      flash[:notice] = 'Your quote was updated'
      send_notification
      redirect_to employee_path
    else
      render action: 'new'
    end
  end

  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to employee_path, notice: 'Line-item was successfully removed.' }
    end
  end
  #Need to consider moving this method to a seperate helper method location and giving it a message for :text based on where the request comes from (e.g. Companies Controller or Quotes Controller). Keeping here for the time being because this is possibly the only use for notifications
  def send_notification
      @emails = EmployeeEmail.all
      if @emails == []
        return
      else
      #rather unwise to have my api key just sitting here in the code, need to check if a new api-key can be generated
      RestClient.post "https://api:key-5f4ada711a8a86a1292bcfe23aa9d0aa"\
      "@api.mailgun.net/v2/sandbox3fcc0ad1e9ee457da78753f228405f7e.mailgun.org/messages",
      :from => "Excited User <mailgun@sandbox3fcc0ad1e9ee457da78753f228405f7e.mailgun.org>",
      :to => send_who_us,
      :subject => "Ovuline Notification Test",
      #ack! I need to find a way to get @company info into this next line
      :text => "This is the Ovuline Notification System test message! A company (need to make this more specific) has submitted information to the Quotes Table! Is that former sentence incomplete or otherwise incorrect? Oh no! A bug!"
      end
  end
    
  def send_who_us
    @emails = EmployeeEmail.all
    @who_array = []
    @emails.each do |f|
        @who_array << f.email
    end
    @who=""
    @who_array.each do |f|
        @who << "#{f}"
        #need to break this down to test it piece by piece
        if f != @who_array[-1]
            @who << ", "
        end
    end
    #this method finishes with this return instead of an end, could cause trouble if @who is ever incorrect
    return @who

end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params[:quote].permit(:id, :adtype, :views, :demographics, :subtotal, :company_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/test.rb
def email_who
    @emails = EmployeeEmail.all


    #for x in :

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>Name: <%= f.text_field :name, :required => true %>
  <p>Company: <%= f.text_field :companyname, :required => true %>
  <p>Email Address: <%= f.email_field :email, :required => true %>
  <p>Phone: <%= f.text_field :phone, :required => true %>

  <p><%= f.submit 'Submit Info', :class => 'button' %>
<% end %>

app/views/companies/edit.html.erb
<div class="everything">
  <div class="header">
    <h1>Editing Company</h1>
  </div>
    <div class="section_teal">
       <div class="section_teal_padding">
        <ul class="large-4 columns">
          <%= render 'form' %>
        </ul>
       </div>
    </div>
</div>
<%= link_to 'Back', employee_path %>

app/views/companies/index.html.erb
<!doctype html>
<html class="no-js" lang="en">
  <div class= "everything">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ovuline Advertising</title>
    <link rel="stylesheet" href="app.css" />
  <!-- <script src="bower_components/modernizr/modernizr.js"></script> --> 
  </head>
  <body>
    <header>
       <img src="images/ovulineadvert.jpg" alt="Ovuline Advertising Logo" />
      <nav>
        <a href="http://www.ovuline.com/">Home</a>
        <a href="#howItWorks">How It Works</a>
        <a href="#services">Services</a>
        <a href="#ourAudience">Our Audience</a>
        <a href="#howWeDesignForYou">Design</a>
        <a href="#successStories">Success Stories</a>
        <a href="url">Log In</a>
      </nav>
    </header>
    <div style="clear:both"></div>
    <main>
      <div class="section_teal">
       <div class="section_teal_padding">
        <ul class="large-4 columns">
          <%= render 'form' %>
        </ul>
       </div>
      </div>
      <div id="howItWorks">
        <h1>How It Works</h1>
        <ul>
          <li>
            <img src="images/workcircle1.jpg" alt="Work Circle 1" />
            <p>Create custom content and ad assets</p>
          </li>
          <li>
            <img src="images/workcircle2.jpg" alt="Work Circle 2" />
            <p>Amplify exposure to assets accross multiple platforms (iOS and Android)</p>
          </li>
          <li>
            <img src="images/workcircle3.jpg" alt="Work Circle 3" />
            <p>Users engage with your ads</p>
          </li>
          <li>
            <img src="images/workcircle4.jpg" alt="Work Circle 4" />
            <p>Receive monthly reports on performance</p>
          </li>
        </ul>
      </div>

      <div id="services">
        <h1>Services</h1>
        <ul>
          <li id="social">
            <img src="images/imageholder.jpg" alt="Image Place Holder">
            <h2>Social</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu molestie tellus. Vivamus eget fermentum mi. Nullam pharetra vitae ex id lacinia. Ut leo nisl, gravida at vulputate quis, tempus vitae lectus. Quisque elementum vulputate ex eget volutpat. Pellentesque finibus mi nec metus hendrerit, a maximus ipsum iaculis. Nam ipsum dui, malesuada vel massa ut, condimentum varius ante. Quisque non nisi felis. Vivamus interdum, velit ut euismod dignissim, eros ligula imperdiet lorem, id euismod erat ligula sit amet dolor.</p>
          </li>
          <li id="oviaExclusives">
            <img src="images/imageholder.jpg" alt="Image Place Holder">
            <h2>Ovia Exclusives</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu molestie tellus. Vivamus eget fermentum mi. Nullam pharetra vitae ex id lacinia. Ut leo nisl, gravida at vulputate quis, tempus vitae lectus. Quisque elementum vulputate ex eget volutpat. Pellentesque finibus mi nec metus hendrerit, a maximus ipsum iaculis. Nam ipsum dui, malesuada vel massa ut, condimentum varius ante. Quisque non nisi felis. Vivamus interdum, velit ut euismod dignissim, eros ligula imperdiet lorem, id euismod erat ligula sit amet dolor.</p>
          </li>
          <li id="email">
            <img src="images/imageholder.jpg" alt="Image Place Holder">
            <h2>Email</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu molestie tellus. Vivamus eget fermentum mi. Nullam pharetra vitae ex id lacinia. Ut leo nisl, gravida at vulputate quis, tempus vitae lectus. Quisque elementum vulputate ex eget volutpat. Pellentesque finibus mi nec metus hendrerit, a maximus ipsum iaculis. Nam ipsum dui, malesuada vel massa ut, condimentum varius ante. Quisque non nisi felis. Vivamus interdum, velit ut euismod dignissim, eros ligula imperdiet lorem, id euismod erat ligula sit amet dolor.</p>
          </li>
          <li id="ads">
            <img src="images/imageholder.jpg" alt="Image Place Holder">
            <h2>Adds</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu molestie tellus. Vivamus eget fermentum mi. Nullam pharetra vitae ex id lacinia. Ut leo nisl, gravida at vulputate quis, tempus vitae lectus. Quisque elementum vulputate ex eget volutpat. Pellentesque finibus mi nec metus hendrerit, a maximus ipsum iaculis. Nam ipsum dui, malesuada vel massa ut, condimentum varius ante. Quisque non nisi felis. Vivamus interdum, velit ut euismod dignissim, eros ligula imperdiet lorem, id euismod erat ligula sit amet dolor.</p>
          </li>
          <li id="articles">
            <img src="images/imageholder.jpg" alt="Image Place Holder">
            <h2>Articles</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu molestie tellus. Vivamus eget fermentum mi. Nullam pharetra vitae ex id lacinia. Ut leo nisl, gravida at vulputate quis, tempus vitae lectus. Quisque elementum vulputate ex eget volutpat. Pellentesque finibus mi nec metus hendrerit, a maximus ipsum iaculis. Nam ipsum dui, malesuada vel massa ut, condimentum varius ante. Quisque non nisi felis. Vivamus interdum, velit ut euismod dignissim, eros ligula imperdiet lorem, id euismod erat ligula sit amet dolor.</p>
          </li>
        </ul>
      </div>

      <div id="ourAudience">
        <h1>Our Audience</h1>
        <img src="images/infographic.jpg" alt="Infographic Content">
      </div>

      <div id="howWeDesignForYou">
        <h1>How We Design For You</h1>
        <img src="images/optimization.jpg" alt="Optimization Content">
        <img src="images/addprocess.jpg" alt="Ads Content">
      </div>

      <div id="successStories">
        <h1>Success Stories</h1>
        <img src="images/weleda.jpg" alt="Weleda Success Story">
        <img src="images/stork.jpg" alt="Stork Success Story">
        <img src="images/premama.jpg" alt="Premama Success Story">
      </div>

      <footer>
         <img src="images/footerimg.jpg" alt="Ovuline Footer" />
      </footer>
    </main>
  </body>
</html>

app/views/companies/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Advertise with Ovuline!</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/show.html.erb
<div class = 'navigation_bar_dashboard'> 
    <ul>
        <a href='/employees'><li>ALL QUOTES</li></a>
        <a href='/employee_email_managers'><li>NOTIFICATION MANAGER</li></a>
    </ul>
</div>

<p id="notice"><%= notice %></p>

<h1><%= @company.companyname %></h1> Contact Name: <%= @company.name %> #: <%= @company.phone %>
<table>
        <tr>
                <td>Campagin Name</td>
                <td>Number of Clicks</td>
                <td>Target Demographics</td>
                <td>Subtotal</td>
        </tr>
        <% @quotes.each do |quote| %>
                <% if quote.company_id == @company.id %>
                <tr>
                        <td><%= quote.location %></td>
                        <td><%= quote.location %></td>
                        <td><%= quote.ttc %></td>
                        <td><%= quote.age %></td>
                        <td><%= quote.weeks_pregnant %></td>
                        <td><%= quote.days_since_signup %></td>
                        <td><%= quote.fertility_condition %></td>
                        <td><%= quote.cycle_stage %></td>
                        <td><%= quote.house_hold_income %></td>
                        <td><%= quote.monthly_acivity %></td>
                        <td><%= quote.budget %></td>
                        <td><%= quote.begin_date %></td>
                        <td><%= quote.begin_date %></td>
                        <td><%= quote.campaign_name %></td>
                        <td><%= quote.ovuline_exclusive %></td>
                        <td><%= quote.native_ad %></td>
                        <td><%= quote.native_article %></td>
                        <td><%= quote.social_ad %></td>


                        <td><%= quote.adtype %></td>
                        <td><%= quote.views %></td>
                        <td><%= link_to "Edit", edit_quote_path(quote) %></td>
                        <td><%= link_to 'Remove', quote, method: :delete %></td>
                </tr>
                <% end %>
        <% end %>
</table>
<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', employee_path %>

app/views/employee_email_managers/_form.html.erb
<%= form_for @email, url: employee_email_managers_path do |f| %>
  <% if @email.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@email.errors.count, "error") %> prohibited this email from being saved:</h2>

      <ul>
      <% @email.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>Name
  <%= f.text_field :name %> </p>
  <!-- Input for :views needs to be contingent on :adtype or a number field -->
    <p>Email
  <%= f.email_field :email %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employee_email_managers/index.html.erb
<div class = 'navigation_bar_dashboard'> 
    <ul>
        <a href='/employees'><li>ALL QUOTES</li></a>
        <a href='/employee_email_managers'><li>NOTIFICATION MANAGER</li></a>
    </ul>
</div>

<h1>Manage who gets email notifications</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>Name</td>
        <td>Email</td>

      </tr>
    <% @emails.each do |email| %>

      <tr>
        <td><%= email.name %></td>
        <td><%= email.email %></td>
        <td><%= link_to 'Show', employee_email_manager_path(email) %></td>
        <td><%= link_to 'Delete', employee_email_manager_path(email), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

    <%= render 'form' %>

app/views/employee_email_managers/show.html.erb
<p>something</p>

app/views/employees/index.html.erb
<div class = 'navigation_bar_dashboard'> 
    <ul>
        <a href='/employees'><li>ALL QUOTES</li></a>
        <a href='/employee_email_managers'><li>NOTIFICATION MANAGER</li></a>
    </ul>
</div>

<p id="notice"><%= notice %></p>

<div class = 'dashboard_table'>
<h1>Company Quotes</h1>

<table>
        <tr>
                <td>Name</td>
                <td>Company</td>
                <td>Email</td>
                <td>Phone</td>
        </tr>
        <% @companies.each do |company| %>
                <tr>
                        <td><%= company.name %></td>
                        <td><%= company.companyname %></td>
                        <td><%= company.email %></td>
                        <td><%= company.phone %></td>
                        <td><%= link_to "Edit", edit_company_path(company) %></td>
                        <td><%= link_to "Show", company %></td>
                        <td><%= link_to "Delete", company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>

        <% end %>

</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OvulineAdCalc</title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
<div class='section_pale_orange'>
 <div class = 'section_general'> 
    <center>
      <h2>Name your Campaign</h2>
        <p><%= f.text_field :campaign_name %></p>

    </center>
  </div>
</div>

  <div class='section_pink outer-v'>
    <div class='section_general inner-v'>

      <center>
        <h2>What is your target audience</h2>
      </center>
      <div class = 'section_pink_padding'>
        <p>Age <%= f.text_field :age %></p>
        <p>Trying to Concieve: <%= f.number_field :ttc %></p>
        <p>Weeks Pregnant: <%= f.number_field :weeks_pregnant %></p>
        <p>Days since signup: <%= f.number_field :days_since_signup %></p>
        <p>Special fertility conditions <%= f.select :fertility_condition, [["Not A Woman", "Not A Woman"]] %> </p>
        <p>Cycle Stage:<%= f.select :cycle_stage, [[],["Something", "Something"]] %> </p>
        <p>Household Income: <%= f.number_field :house_hold_income %> </p>
        <p>30-Day App Activity: <%= f.select :monthly_acivity, [['Low', "Low"], ['Medium'], ['High', 'High']] %> </p>
        </div>
      </div>
    </div>
  </div>

<div class = 'section_teal'>
  <div class = 'section_general'>
  <center>
    <h2>Budget</h2>
  </center>
    <div class = 'section_teal_padding'>
      <p>Monthly Advertizing Budget <%= f.number_field :budget %></p>
      <p>Begining of Campaign <%= f.text_field :begin_date %> </p> <p>End of Campaign <%= f.text_field :end_date %></p>
    </div>
  </div>
</div>

<div class = 'section_light_blue'>
<div class = 'section_general'>
  <center>
    <h2> Prefered Ad Types</h2>

      <p>Adtype: <%= f.text_field :adtype %>
      <p>Social Ad <%= f.check_box(:social_ad) %> Ovia Exclusives <%= check_box_tag(:ovuline_exclusive) %></p>
      <p>Native Ad <%= f.check_box(:native_ad) %> Native Article <%= check_box_tag(:native_article)%></p>

     <p>What is you goal in number of impressions / click throughs </p>
      <%= f.number_field :views %> </p>

        <%= f.submit 'Submit Info', :class => 'button' %>

  </center>
  </div>
</div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', employee_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Thanks for your interest, we'll be in touch!</h1>

app/views/quotes/new.html.erb
<p id="notice"><%= notice %></p>

<div class = 'navigation_bar'>
    
    <ul>

        <a><li>HOME</li></a>
        <a><li>HOW IT WORKS</li></a>
        <a><li>OUR AUDIENCE</li></a>
        <a><li>SERVICES</li></a>
        <a><li>DESIGN</li></a>
        <a><li>SUCCESS STORIES</li></a>

    </ul>

</div>

    <%= render 'form' %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>
<table>
        <tr>
                <td>Ad Type</td>
                <td>Number of Clicks</td>
                <td>Target Demographics</td>
                <td>Subtotal</td>
        </tr>
        <% @quotes.each do |quote| %>
                <tr>
                        <td><%= quote.adtype %></td>
                        <td><%= quote.views %></td>
                        <td><%= quote.demographics %></td>
                        <td><%= quote.subtotal %></td>
                        <td><%= link_to "Back",  %></td>
                        <td><%= link_to "Edit", edit_quote_path(quote) %></td>
                        <td><%= link_to "Delete", company, method: :delete %></td>
                </tr>
        <% end %>
</table>